/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package preventivemaintenance;

import java.awt.Color;
import java.io.File;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author Admin
 */
public class APM extends javax.swing.JFrame  {

    /**
     * Creates new form APM
     */
    public APM() {
        initComponents();
        
      
PromptSupport.setPrompt("Employee Name", txtEmpName);
PromptSupport.setPrompt("Location", txtLocation);
PromptSupport.setPrompt("Asset Code", txtAssetCode);
PromptSupport.setPrompt("Department", txtDept);




    }
    private String lblStr = "";
    public APM( String lblStr ) {
		this.lblStr = lblStr;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtEmpName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtAssetCode = new javax.swing.JTextField();
        txtDept = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        chk1_7n = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chk1_1y = new javax.swing.JCheckBox();
        chk1_1n = new javax.swing.JCheckBox();
        chk1_2y = new javax.swing.JCheckBox();
        chk1_2n = new javax.swing.JCheckBox();
        chk1_3y = new javax.swing.JCheckBox();
        chk1_3n = new javax.swing.JCheckBox();
        chk1_4y = new javax.swing.JCheckBox();
        chk1_4n = new javax.swing.JCheckBox();
        chk1_5y = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        chk1_5n = new javax.swing.JCheckBox();
        chk1_6y = new javax.swing.JCheckBox();
        chk1_6n = new javax.swing.JCheckBox();
        chk1_7y = new javax.swing.JCheckBox();
        txtR1_1 = new javax.swing.JTextField();
        txtAt1_2 = new javax.swing.JTextField();
        txtR1_2 = new javax.swing.JTextField();
        txtAt1_3 = new javax.swing.JTextField();
        txtR1_3 = new javax.swing.JTextField();
        txtAt1_4 = new javax.swing.JTextField();
        txtR1_4 = new javax.swing.JTextField();
        txtAt1_5 = new javax.swing.JTextField();
        txtR1_5 = new javax.swing.JTextField();
        txtAt1_6 = new javax.swing.JTextField();
        txtR1_6 = new javax.swing.JTextField();
        txtAt1_7 = new javax.swing.JTextField();
        txtR1_7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtR1_8 = new javax.swing.JTextField();
        txtR1_9 = new javax.swing.JTextField();
        txtR1_10 = new javax.swing.JTextField();
        txtR1_11 = new javax.swing.JTextField();
        txtR1_12 = new javax.swing.JTextField();
        txtAt1_1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtR1_13 = new javax.swing.JTextField();
        txtR1_14 = new javax.swing.JTextField();
        txtR1_15 = new javax.swing.JTextField();
        txtR1_16 = new javax.swing.JTextField();
        txtR1_17 = new javax.swing.JTextField();
        txtR1_18 = new javax.swing.JTextField();
        txtR1_19 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtR1_25 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtR1_26 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtR1_27 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtR1_28 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtR1_29 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtR1_30 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtR1_31 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        chk1_5n1 = new javax.swing.JCheckBox();
        txtAt1_8 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        chk1_4n1 = new javax.swing.JCheckBox();
        txtR1_32 = new javax.swing.JTextField();
        chk1_5y1 = new javax.swing.JCheckBox();
        txtAt1_11 = new javax.swing.JTextField();
        txtAt1_12 = new javax.swing.JTextField();
        txtR1_36 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtAt1_9 = new javax.swing.JTextField();
        chk1_3y1 = new javax.swing.JCheckBox();
        txtR1_34 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        chk1_3n1 = new javax.swing.JCheckBox();
        chk1_1n1 = new javax.swing.JCheckBox();
        txtR1_33 = new javax.swing.JTextField();
        jCheckBox12 = new javax.swing.JCheckBox();
        chk1_1y1 = new javax.swing.JCheckBox();
        chk1_4y1 = new javax.swing.JCheckBox();
        chk1_2y1 = new javax.swing.JCheckBox();
        txtR1_35 = new javax.swing.JTextField();
        chk1_2n1 = new javax.swing.JCheckBox();
        txtAt1_10 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        chk1_5n2 = new javax.swing.JCheckBox();
        chk1_4n2 = new javax.swing.JCheckBox();
        chk1_5y2 = new javax.swing.JCheckBox();
        txtAt1_13 = new javax.swing.JTextField();
        txtR1_37 = new javax.swing.JTextField();
        jCheckBox13 = new javax.swing.JCheckBox();
        chk1_4y2 = new javax.swing.JCheckBox();
        txtR1_38 = new javax.swing.JTextField();
        txtAt1_14 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmpName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtEmpName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmpName.setToolTipText("Employee Name");
        txtEmpName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });
        jPanel10.add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 400, 40));

        txtLocation.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 400, 40));

        txtAssetCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAssetCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAssetCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAssetCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssetCodeActionPerformed(evt);
            }
        });
        jPanel10.add(txtAssetCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 400, 40));

        txtDept.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtDept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(txtDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 400, 40));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 920, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/preventivemaintenance/images/AIRSPEED_LOGO_Transparent-2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> <center> Preventive Maintenance Checklist System <br> Airspeed International Corporation<br> MIS Department </center> </html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 450, 60));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("R-AIC-MIS-011");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 180, 120));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 920, 30));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel5.setPreferredSize(new java.awt.Dimension(910, 351));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk1_7n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_7n.setBorderPainted(true);
        chk1_7n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_7n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remarks");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 180, 30));

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText("NEXT >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel5.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Remarks");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 480, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NO");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Action Taken");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 180, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("YES");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 30));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("1.2 Are the workstation dust free?");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 480, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("1.3 Is the workstation in good location?");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("1.4 Is the Asset Code still intact?");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 480, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("1.5 Does the keyboard functions properly?");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 480, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("1.6 Does the mouse functions properly?");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 480, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("1.1 Are the computer cables managed properly?");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setOpaque(true);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 30));

        chk1_1y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_1y.setBorderPainted(true);
        chk1_1y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chk1_1y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chk1_1yMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chk1_1yMouseExited(evt);
            }
        });
        jPanel5.add(chk1_1y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 60, 30));

        chk1_1n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_1n.setBorderPainted(true);
        chk1_1n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_1n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 60, 30));

        chk1_2y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_2y.setBorderPainted(true);
        chk1_2y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_2y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 60, 30));

        chk1_2n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_2n.setBorderPainted(true);
        chk1_2n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_2n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 60, 30));

        chk1_3y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_3y.setBorderPainted(true);
        chk1_3y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_3y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 60, 30));

        chk1_3n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_3n.setBorderPainted(true);
        chk1_3n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_3n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 60, 30));

        chk1_4y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4y.setBorderPainted(true);
        chk1_4y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_4y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 60, 30));

        chk1_4n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4n.setBorderPainted(true);
        chk1_4n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_4n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 60, 30));

        chk1_5y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5y.setBorderPainted(true);
        chk1_5y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_5y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 60, 30));

        jCheckBox11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox11.setBorderPainted(true);
        jCheckBox11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 60, 30));

        chk1_5n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5n.setBorderPainted(true);
        chk1_5n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_5n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 60, 30));

        chk1_6y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_6y.setBorderPainted(true);
        chk1_6y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_6y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 60, 30));

        chk1_6n.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_6n.setBorderPainted(true);
        chk1_6n.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_6n, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 60, 30));

        chk1_7y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_7y.setBorderPainted(true);
        chk1_7y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(chk1_7y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 60, 30));

        txtR1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 180, 30));

        txtAt1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAt1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAt1_2ActionPerformed(evt);
            }
        });
        jPanel5.add(txtAt1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 180, 30));

        txtR1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 180, 30));

        txtAt1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAt1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAt1_3ActionPerformed(evt);
            }
        });
        jPanel5.add(txtAt1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 180, 30));

        txtR1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 180, 30));

        txtAt1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtAt1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 180, 30));

        txtR1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 180, 30));

        txtAt1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtAt1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 180, 30));

        txtR1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 180, 30));

        txtAt1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtAt1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 180, 30));

        txtR1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 180, 30));

        txtAt1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtAt1_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 180, 30));

        txtR1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("1.13 Check Printer Connection/Quality");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 480, 30));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 480, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("1.7 Does the AVR/UPS status are in good condition?");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 480, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("1.9 Inspect Unit for unusual noise");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 480, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("1.10 CPU Casing Status");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 480, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("1.11 Monitor Display Condition");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 480, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("1.12 Power switches status");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 480, 30));

        txtR1_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 480, 30));

        txtR1_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 480, 30));

        txtR1_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 480, 30));

        txtR1_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 480, 30));

        txtR1_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtR1_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 480, 30));

        txtAt1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(txtAt1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 180, 30));

        jTabbedPane1.addTab("1. Physical Hardware Maintenance", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel26.setText("(OS and hard disk health status)");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 470, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel40.setText("(no. of removed unnecessary files)");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 470, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel41.setText("(size of cleaned storage)");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 470, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel42.setText("(cleared cache on browser)");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 470, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel43.setText("(last OS update)");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 470, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel25.setText("(Outlook PST File Size)");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 470, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel24.setText("(check for the optimization schedule)");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 470, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("<< PREVIOUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 890, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Remarks");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 480, 30));

        btnNext1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext1.setText("NEXT >>");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 890, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Active Directory Controls");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 480, 30));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("2.2 Run disk scan and System File Checker");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 480, 50));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("2.3 Remove unnecessary Apps and Files");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 480, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("2.4 Run Disk Cleanup");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 480, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("2.5 Clear cache on browser");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 480, 50));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("2.6 Update Computer OS");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 480, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("2.1 Last Defragmentation result");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 50));

        txtR1_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 480, 50));

        txtR1_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 480, 50));

        txtR1_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 480, 50));

        txtR1_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 480, 50));

        txtR1_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 480, 50));

        txtR1_18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 480, 50));

        txtR1_19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 480, 50));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("2.17 Does the unit has limited access to control panel?");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 480, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("2.7 Check Outlook file");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 480, 50));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("2.13 Does the unit has standard wallpaper?");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 480, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("2.14 Does the unit shows corporate slideshow when locked?");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 480, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("2.15 Does the unit blocks USB Port?");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 480, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("2.16 Does the unit has awareness message before login?");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 480, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel44.setText("(PING test result)");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 470, 30));

        txtR1_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 480, 50));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("2.8 Ping test on gateway and external website result");
        jLabel45.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 480, 50));

        jLabel46.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel46.setText("(disabled startup application)");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 470, 30));

        txtR1_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 480, 50));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("2.9 Disable startup application");
        jLabel47.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 480, 50));

        jLabel48.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel48.setText("(PING test result)");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 470, 30));

        txtR1_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 480, 50));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("2.8 Ping test on gateway and external website result");
        jLabel49.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 480, 50));

        jLabel50.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel50.setText("(date and timestamp)");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 470, 30));

        txtR1_28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 480, 50));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("2.10 Date and timestamp synchronized?");
        jLabel51.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 480, 50));

        txtR1_29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 480, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("2.11 Windows Edition");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 480, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel54.setText("(date and timestamp)");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 470, 30));

        txtR1_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 480, 50));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("2.10 Date and timestamp synchronized?");
        jLabel55.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 480, 50));

        txtR1_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 480, 30));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("2.12 Windows Version");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 480, 30));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 960, 30));

        chk1_5n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5n1.setBorderPainted(true);
        chk1_5n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_5n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 770, 60, 30));

        txtAt1_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAt1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAt1_8ActionPerformed(evt);
            }
        });
        jPanel6.add(txtAt1_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 680, 180, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("NO");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 60, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Action Taken");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 180, 30));

        chk1_4n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4n1.setBorderPainted(true);
        chk1_4n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_4n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 740, 60, 30));

        txtR1_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 180, 30));

        chk1_5y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5y1.setBorderPainted(true);
        chk1_5y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_5y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 770, 60, 30));

        txtAt1_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAt1_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 770, 180, 30));

        txtAt1_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAt1_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 180, 30));

        txtR1_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 770, 180, 30));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("YES");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 60, 30));

        txtAt1_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAt1_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAt1_9ActionPerformed(evt);
            }
        });
        jPanel6.add(txtAt1_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 180, 30));

        chk1_3y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_3y1.setBorderPainted(true);
        chk1_3y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_3y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, 60, 30));

        txtR1_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 710, 180, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Remarks");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 180, 30));

        chk1_3n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_3n1.setBorderPainted(true);
        chk1_3n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_3n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 60, 30));

        chk1_1n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_1n1.setBorderPainted(true);
        chk1_1n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_1n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 60, 30));

        txtR1_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 680, 180, 30));

        jCheckBox12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox12.setBorderPainted(true);
        jCheckBox12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 770, 60, 30));

        chk1_1y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_1y1.setBorderPainted(true);
        chk1_1y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_1y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 60, 30));

        chk1_4y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4y1.setBorderPainted(true);
        chk1_4y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_4y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 740, 60, 30));

        chk1_2y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_2y1.setBorderPainted(true);
        chk1_2y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_2y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 60, 30));

        txtR1_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 740, 180, 30));

        chk1_2n1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_2n1.setBorderPainted(true);
        chk1_2n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_2n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 60, 30));

        txtAt1_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAt1_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, 180, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("2.19 Does unit Disable Guest Account");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 480, 30));

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel61.setText("2.18 Does the unit automatically locks after 10mins?");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 800, 480, 30));

        chk1_5n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5n2.setBorderPainted(true);
        chk1_5n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_5n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 830, 60, 30));

        chk1_4n2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4n2.setBorderPainted(true);
        chk1_4n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_4n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 800, 60, 30));

        chk1_5y2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_5y2.setBorderPainted(true);
        chk1_5y2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_5y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 830, 60, 30));

        txtAt1_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAt1_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 830, 180, 30));

        txtR1_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 830, 180, 30));

        jCheckBox13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheckBox13.setBorderPainted(true);
        jCheckBox13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 830, 60, 30));

        chk1_4y2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chk1_4y2.setBorderPainted(true);
        chk1_4y2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(chk1_4y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 800, 60, 30));

        txtR1_38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtR1_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 800, 180, 30));

        txtAt1_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAt1_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 800, 180, 30));

        jTabbedPane1.addTab("2. Workstation Performance Maintenance", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("3. Employee Awareness", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("4. Information Security Requirements Maintenance", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("5. Workstation Information", jPanel9);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 970, 1000));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 1230));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1160, 990, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jTabbedPane1.setEnabledAt(1, false);
jTabbedPane1.setEnabledAt(2, false);
jTabbedPane1.setEnabledAt(3, false);
jTabbedPane1.setEnabledAt(4, false);


    }//GEN-LAST:event_formWindowActivated

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         int currentIndex = jTabbedPane1.getSelectedIndex();
int nextIndex = (currentIndex + 1) % jTabbedPane1.getTabCount();
jTabbedPane1.setSelectedIndex(nextIndex);

jTabbedPane1.setEnabledAt(1, true);


// a method to generate the report, by assigning the prameter to their value, and calling te generate report method

//Map param = new HashMap();
//param.put("emp_name",this.txtAt1_1.getText());
//
//generateReports("ImpresionPdfImagenes", param);


    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int currentIndex = jTabbedPane1.getSelectedIndex();
int nextIndex = (currentIndex - 1) % jTabbedPane1.getTabCount();
jTabbedPane1.setSelectedIndex(nextIndex);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtAssetCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssetCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssetCodeActionPerformed

    private void txtAt1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAt1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAt1_2ActionPerformed

    private void txtAt1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAt1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAt1_3ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void txtAt1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAt1_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAt1_8ActionPerformed

    private void txtAt1_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAt1_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAt1_9ActionPerformed

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
		jLabel18.setForeground(new Color(0, 51, 255));
		   
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        jLabel18.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabel18MouseExited

    private void chk1_1yMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk1_1yMouseEntered
        // TODO add your handling code here:
     
        jLabel18.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_chk1_1yMouseEntered

    private void chk1_1yMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk1_1yMouseExited
        // TODO add your handling code here:
         jLabel18.setForeground(new Color(0, 0, 0));
          jLabel18.setBackground(null);
    }//GEN-LAST:event_chk1_1yMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JCheckBox chk1_1n;
    private javax.swing.JCheckBox chk1_1n1;
    private javax.swing.JCheckBox chk1_1y;
    private javax.swing.JCheckBox chk1_1y1;
    private javax.swing.JCheckBox chk1_2n;
    private javax.swing.JCheckBox chk1_2n1;
    private javax.swing.JCheckBox chk1_2y;
    private javax.swing.JCheckBox chk1_2y1;
    private javax.swing.JCheckBox chk1_3n;
    private javax.swing.JCheckBox chk1_3n1;
    private javax.swing.JCheckBox chk1_3y;
    private javax.swing.JCheckBox chk1_3y1;
    private javax.swing.JCheckBox chk1_4n;
    private javax.swing.JCheckBox chk1_4n1;
    private javax.swing.JCheckBox chk1_4n2;
    private javax.swing.JCheckBox chk1_4y;
    private javax.swing.JCheckBox chk1_4y1;
    private javax.swing.JCheckBox chk1_4y2;
    private javax.swing.JCheckBox chk1_5n;
    private javax.swing.JCheckBox chk1_5n1;
    private javax.swing.JCheckBox chk1_5n2;
    private javax.swing.JCheckBox chk1_5y;
    private javax.swing.JCheckBox chk1_5y1;
    private javax.swing.JCheckBox chk1_5y2;
    private javax.swing.JCheckBox chk1_6n;
    private javax.swing.JCheckBox chk1_6y;
    private javax.swing.JCheckBox chk1_7n;
    private javax.swing.JCheckBox chk1_7y;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAssetCode;
    private javax.swing.JTextField txtAt1_1;
    private javax.swing.JTextField txtAt1_10;
    private javax.swing.JTextField txtAt1_11;
    private javax.swing.JTextField txtAt1_12;
    private javax.swing.JTextField txtAt1_13;
    private javax.swing.JTextField txtAt1_14;
    private javax.swing.JTextField txtAt1_2;
    private javax.swing.JTextField txtAt1_3;
    private javax.swing.JTextField txtAt1_4;
    private javax.swing.JTextField txtAt1_5;
    private javax.swing.JTextField txtAt1_6;
    private javax.swing.JTextField txtAt1_7;
    private javax.swing.JTextField txtAt1_8;
    private javax.swing.JTextField txtAt1_9;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtR1_1;
    private javax.swing.JTextField txtR1_10;
    private javax.swing.JTextField txtR1_11;
    private javax.swing.JTextField txtR1_12;
    private javax.swing.JTextField txtR1_13;
    private javax.swing.JTextField txtR1_14;
    private javax.swing.JTextField txtR1_15;
    private javax.swing.JTextField txtR1_16;
    private javax.swing.JTextField txtR1_17;
    private javax.swing.JTextField txtR1_18;
    private javax.swing.JTextField txtR1_19;
    private javax.swing.JTextField txtR1_2;
    private javax.swing.JTextField txtR1_25;
    private javax.swing.JTextField txtR1_26;
    private javax.swing.JTextField txtR1_27;
    private javax.swing.JTextField txtR1_28;
    private javax.swing.JTextField txtR1_29;
    private javax.swing.JTextField txtR1_3;
    private javax.swing.JTextField txtR1_30;
    private javax.swing.JTextField txtR1_31;
    private javax.swing.JTextField txtR1_32;
    private javax.swing.JTextField txtR1_33;
    private javax.swing.JTextField txtR1_34;
    private javax.swing.JTextField txtR1_35;
    private javax.swing.JTextField txtR1_36;
    private javax.swing.JTextField txtR1_37;
    private javax.swing.JTextField txtR1_38;
    private javax.swing.JTextField txtR1_4;
    private javax.swing.JTextField txtR1_5;
    private javax.swing.JTextField txtR1_6;
    private javax.swing.JTextField txtR1_7;
    private javax.swing.JTextField txtR1_8;
    private javax.swing.JTextField txtR1_9;
    // End of variables declaration//GEN-END:variables
//private void generateReport(String inputtedName) throws JRException {
//    JasperReport jasperReport = JasperCompileManager.compileReport("apmReport.jrxml");
//    Map<String, Object> parameters = new HashMap<>();
//    parameters.put("emp_name", inputtedName);
//    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());
//    JasperViewer.viewReport(jasperPrint, false);
//}
    private void generateReports (String name, Map param ){
try{
String source = "C:\\Users\\Admin\\Documents\\GitHub\\AirspeedPreventiveMaintenance\\src\\preventivemaintenance\\apmReport.jrxml";
if (new File(source).exists() == false) {
// xputils.showMessage(“Please go report file does not exst”);
return;
}
JasperReport jasperReport = JasperCompileManager.compileReport(source);
JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,new JREmptyDataSource());
JasperViewer.viewReport(jasperPrint, false);
} catch (Exception e){
e.printStackTrace();
System.out.println("reports Error" + e.toString());
}
}
}
